START TRANSACTION;
UPDATE PERSONAS SET TELEFONO = 5113433817 WHERE ID_PERSONA >1;
ROLLBACK;

START TRANSACTION;
INSERT INTO `reservas_naturales`.`zonas`
(`id_zona`,
`nombre`,
`descripcion`)
VALUES
(4,'ZONA PRUEBA 1','DESCRIPCION PRUEBA'),
(5,'ZONA PRUEBA 2','DESCRIPCION PRUEBA');
SAVEPOINT LOTE1;
INSERT INTO `reservas_naturales`.`zonas`
(`id_zona`,
`nombre`,
`descripcion`)
VALUES
(6,'ZONA PRUEBA 3','DESCRIPCION PRUEBA'),
(7,'ZONA PRUEBA 4','DESCRIPCION PRUEBA');
SAVEPOINT LOTE2;
RELEASE SAVEPOINT LOTE1;
